/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/g1.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Girl1(props) {
  const { scene } = useGLTF('/g1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.hip} />
        <primitive object={nodes.new_gens_V8_1840} />
        <mesh geometry={nodes['New_Genitalia_For_Victoria_8_-_Effect_LayerShape'].geometry} material={materials.new_gens_V8_1840_Genitalia} />
        <mesh geometry={nodes.Geometry_Shell_3_1.geometry} material={materials['new_gens_V8_1840_Genitalia.001']} />
        <mesh geometry={nodes.Geometry_Shell_3_2.geometry} material={materials['new_gens_V8_1840_Anus.001']} />
        <skinnedMesh geometry={nodes.Genesis8Female_1.geometry} material={materials.Torso} skeleton={nodes.Genesis8Female_1.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_2.geometry} material={materials.Face} skeleton={nodes.Genesis8Female_2.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_3.geometry} material={materials.Lips} skeleton={nodes.Genesis8Female_3.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_4.geometry} material={materials.Teeth} skeleton={nodes.Genesis8Female_4.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_5.geometry} material={materials.Ears} skeleton={nodes.Genesis8Female_5.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_6.geometry} material={materials.Legs} skeleton={nodes.Genesis8Female_6.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_7.geometry} material={materials.EyeSocket} skeleton={nodes.Genesis8Female_7.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_8.geometry} material={materials.Mouth} skeleton={nodes.Genesis8Female_8.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_9.geometry} material={materials.Arms} skeleton={nodes.Genesis8Female_9.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_10.geometry} material={materials.Pupils} skeleton={nodes.Genesis8Female_10.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_11.geometry} material={materials.EyeMoisture} skeleton={nodes.Genesis8Female_11.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_12.geometry} material={materials.Fingernails} skeleton={nodes.Genesis8Female_12.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_13.geometry} material={materials.Cornea} skeleton={nodes.Genesis8Female_13.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_14.geometry} material={materials.Irises} skeleton={nodes.Genesis8Female_14.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_15.geometry} material={materials.Sclera} skeleton={nodes.Genesis8Female_15.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_16.geometry} material={materials.Toenails} skeleton={nodes.Genesis8Female_16.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_17.geometry} material={materials.Genitalia} skeleton={nodes.Genesis8Female_17.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8Female_18.geometry} material={materials.Anus} skeleton={nodes.Genesis8Female_18.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8FemaleEyelashes.geometry} material={materials['EyeMoisture.001']} skeleton={nodes.Genesis8FemaleEyelashes.skeleton} />
        <skinnedMesh geometry={nodes.Genesis8FemaleEyelashes_1.geometry} material={materials.Eyelashes} skeleton={nodes.Genesis8FemaleEyelashes_1.skeleton} />
      </group>
      <group position={[0.008, 0.077, 0.006]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.hip_1} />
        <skinnedMesh geometry={nodes.Pubic24_65898Shape.geometry} material={materials.pubic_hair} skeleton={nodes.Pubic24_65898Shape.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/g1.glb')
