/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/viorel.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { Environment, OrbitControls, useGLTF, useFBX, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'


export function Viorel(props) {
  
  const group = React.useRef()
  const { scene, animations } = useGLTF('/viorel.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const { animations: anims2 } = useFBX("animations/armada.fbx")
  anims2[0].name = 'pontera'
  console.log(anims2)
  const { actions } = useAnimations(anims2, group)
  console.log(actions)
  
    useEffect(() => {
    actions['pontera'].reset().setLoop('LoopOnce', 1).play()
  }, [])
  return (
    <>
    <OrbitControls />
    <ambientLight intensity={1.0} />
    <Environment preset="sunset" />
    <directionalLight position={[5, 5, 5]} intensity={2.0} castShadow />
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="avaturn_body" geometry={nodes.avaturn_body.geometry} material={materials.avaturn_body_material} skeleton={nodes.avaturn_body.skeleton} />
          <skinnedMesh name="avaturn_glasses_0" geometry={nodes.avaturn_glasses_0.geometry} material={materials.avaturn_glasses_0_material} skeleton={nodes.avaturn_glasses_0.skeleton} />
          <skinnedMesh name="avaturn_glasses_1" geometry={nodes.avaturn_glasses_1.geometry} material={materials.avaturn_glasses_1_material} skeleton={nodes.avaturn_glasses_1.skeleton} />
          <skinnedMesh name="avaturn_hair_0" geometry={nodes.avaturn_hair_0.geometry} material={materials.avaturn_hair_0_material} skeleton={nodes.avaturn_hair_0.skeleton} />
          <skinnedMesh name="avaturn_shoes_0" geometry={nodes.avaturn_shoes_0.geometry} material={materials.avaturn_shoes_0_material} skeleton={nodes.avaturn_shoes_0.skeleton} />
          <skinnedMesh name="avaturn_look_0" geometry={nodes.avaturn_look_0.geometry} material={materials.avaturn_look_0_material} skeleton={nodes.avaturn_look_0.skeleton} />
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/viorel.glb')
